[package]
name = "qm-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "qm-mcp"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
object_store = { workspace = true }
qm-cli = { workspace = true }
qm-core = { workspace = true }
rmcp = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
object_store = { workspace = true }
serde_json = { workspace = true }
